language: node_js
node_js:
  - 12

services:
  - docker

# Build
script:
  - docker build -t udagram-api-user .
# Tagging
  - docker tag udagram-api-user tatthang0501/udagram-api-user:v1
# Do similar for other three images

# Push
# Assuming DOCKER_PASSWORD and DOCKER_USERNAME are set in the Travis repository settings
after_success:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push tatthang0501/udagram-api-user:v1
# Do similar for other three images